server:
  port: 9090
  ssl:    # 내장서버 구성할때
    key-store: file://path/to/mykeys.jks
    key-store-password: letmein
    key-password: letmein

spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud  #데이터베이스 연결
    username: tacodb
    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
    schema:                                # 애플리케이션이 시작될떄 sql스크립트가 실행되도록 설정
      - order-schema.sql
      - ingredient-schema.sql
      - taco-schema.sql
      - user-schema.sql
    data:
      - ingredient.sql
    jndi-name: java:/comp/env/jdbc/tacoCloudDS  # 명시적인 데이터 소스 구성 대신 JNDI에 구성하고싶을때 설정(설정하면 다른 데이터 소스 구성 속성은 무시됨)

##### 로깅 구성
logging:
  file: TacoCloud.log
    path: /var/logs
  level:
    root: warn
    org:
      springframework:
        security: DEBUG

# 페이지 설정
taco:
  orders:
    pageSize: 10



--- #application.yml은 3개의 하이픈을 기준으로 구분된다
# 프로파일 특정 속성을 지정할때
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
logging:
  level:
    tacos: WARN